networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:13
    container_name: threads-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myappdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d myappdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: gomicro/goose
    container_name: threads-migrator
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://postgres:postgres@postgres:5432/myappdb?sslmode=disable"
    volumes:
      - ./migrations:/migrations
    command: goose -dir /migrations up
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  app:
    container_name: threads-app
    build: .
    restart: always
    ports:
      - "8082:8082"
      - "50052:50052"
      - "5432:5432"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - CONFIG_PATH=./configs/config.yaml
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

volumes:
  db_data:
